### ISSUE TITLE
dane do projektu

### ISSUE THREAD

**Issue by juustte** [mmagnuski/mozg-rozpajton#24]
Gdzie konkretnie znajdują się dane na których mamy opracować projekt? Z ilu plików mamy korzystać?

**Comment by mmagnuski** [comment]
na Dropboxie w folderze `clean epochs` są pliki do ERPów, a w `DiamDec/preproc SET` są pliki do czasu-częstości.
Możecie korzystać ze wszystkich plików, myślę że nie ma sensu ograniczać ich liczbę - wczytują się rach-ciach.
