### ISSUE TITLE
PD0

### ISSUE THREAD

**Issue by mmagnuski** [mmagnuski/mozg-rozpajton#9]
Zapraszam do Klubu Kraba Kawalarza!

**Comment by gacek91** [comment]
![zrzut ekranu 2016-11-29 o 10 46 56](https://cloud.githubusercontent.com/assets/19230487/20704891/2f9def06-b621-11e6-961e-53f3dadb42b6.png)

**Comment by mmagnuski** [comment]
🦀 Krab Kawalarz czeka na kolejnych gości 🦀

**Comment by kasiado** [comment]
![screenshot 2016-12-01 11 55 38](https://cloud.githubusercontent.com/assets/19713774/20792365/9a896aa6-b7c1-11e6-8a82-d10735d1f27d.jpg)

**Comment by wiktoriakowalczyk** [comment]
![zrzut ekranu 2016-12-01 o 14 34 09](https://cloud.githubusercontent.com/assets/19744508/20795786/4b83002c-b7d3-11e6-89be-921d858f859f.png)

**Comment by jakubmatyszewski** [comment]
hehe
![image](https://cloud.githubusercontent.com/assets/15054592/20804483/5b32929c-b7f3-11e6-91a0-5d338e4e451a.png)

**Comment by kuchart** [comment]
![screen shot 2016-12-01 at 7 29 17 pm](https://cloud.githubusercontent.com/assets/19734426/20806794/8edddc88-b7fc-11e6-9232-673b85a29ca1.png)

**Comment by juustte** [comment]
![zrzut ekranu 2016-12-01 o 19 48 35](https://cloud.githubusercontent.com/assets/19696992/20807450/3ee6e3e8-b7ff-11e6-95e4-b4bc7b3585db.png)

**Comment by AnnaMayDi** [comment]
<img width="1127" alt="zrzut ekranu 2016-12-01 o 20 39 33" src="https://cloud.githubusercontent.com/assets/19490551/20809468/70563288-b806-11e6-8620-70cc1ab08746.png">

**Comment by majcherkasia** [comment]
![pd1](https://cloud.githubusercontent.com/assets/24196651/20811985/255219e6-b810-11e6-910c-05e1fa60f9d7.JPG)

**Comment by kpijor** [comment]
![hura](https://cloud.githubusercontent.com/assets/18737953/20812048/76a2c836-b810-11e6-9e21-9cd82762813c.JPG)

**Comment by majmis** [comment]
<img width="483" alt="obraz bez nazwy" src="https://cloud.githubusercontent.com/assets/19708809/20814904/ecf46f16-b81b-11e6-9cd7-1ce9c73251f2.png">

**Comment by moniakow** [comment]
![zrzut ekranu 2016-12-01 o 23 38 26](https://cloud.githubusercontent.com/assets/18737946/20815717/4cc3a0da-b81f-11e6-99db-86c1f30133ec.png)

**Comment by hubertwoz** [comment]
![zrzut ekranu 2016-12-01 godz 23 45 10](https://cloud.githubusercontent.com/assets/19748936/20815943/42b9ba9c-b820-11e6-9174-c7673a618253.png)

**Comment by violettaz** [comment]
![krabik](https://cloud.githubusercontent.com/assets/19698274/20816013/97b340ae-b820-11e6-9b6f-ef5701d5c30d.png)

**Comment by Emilia-Szczuchniak** [comment]
![zrzut ekranu 2](https://cloud.githubusercontent.com/assets/24305580/20818544/98c3f6a6-b82e-11e6-9179-0dfdc43229c0.png)

**Comment by Emilia-Szczuchniak** [comment]
![zero](https://cloud.githubusercontent.com/assets/24305580/20818619/1a3c5c64-b82f-11e6-8bc1-174edcee039e.png)

**Comment by joazamojska** [comment]
![bez tytulu](https://cloud.githubusercontent.com/assets/19728048/20826247/d6962a7c-b869-11e6-8a8c-71d42a1d3053.jpg)

**Comment by inezgiemza** [comment]
![zrzut ekranu 2016-12-02 o 09 11 25](https://cloud.githubusercontent.com/assets/19704300/20827160/5fe1f5ee-b870-11e6-884b-73fdb843327d.png)

**Comment by Mariszka** [comment]
![przechwytywanie](https://cloud.githubusercontent.com/assets/18737950/20827313/750a50fa-b871-11e6-8cd4-816885647c1a.PNG)

**Comment by FNCY** [comment]
![image](https://cloud.githubusercontent.com/assets/19698186/20831958/d6c3b19a-b887-11e6-8958-aa09571ab94a.png)

**Comment by mmagnuski** [comment]
Drodzy kawalarze, kawalarki (?) - dziękuję za zjawienie się na dzisiejszej imprezie.
BTW - w folderze `notebooks` macie notebook z dzisiejszych zajęć - możecie go sobie ściągnąć i się nim pobawić.
:email: epocztą wyślę Wam informację jak usmażę Wam jakąś straszną pracę domową :smiling_imp: 
Pamiętajcie też o możliwości nie w pełni zapowiedzianej kartkówki na następnych zajęciach :memo:

**Comment by mraciborski** [comment]
Podobno lepiej późno niż wcale.
![1478867028_by_cenot_500](https://cloud.githubusercontent.com/assets/19710532/21033022/e84d28b2-bdad-11e6-9f6a-ef4bf4794799.jpg)

**Comment by EIsakova** [comment]
![ekaterina isakova](https://cloud.githubusercontent.com/assets/25300203/22214891/ae7740d6-e199-11e6-99d0-20373eb303c1.jpg)

**Comment by mazaw** [comment]
![zrzut ekranu 2017-03-09 o 11 29 27](https://cloud.githubusercontent.com/assets/23727429/23746298/b764bd3c-04bb-11e7-8293-5394ab2f05f9.png)

**Comment by mmagnuski** [comment]
@mazaw 
3 miesiące poślizgu to trochę za dużo 😄

**Comment by mazaw** [comment]
Musiałam chyba wstawić w złe miejsce, bo jestem z grupy, która dopiero
zaczęła zajęcia w tym semestrze 😉

W dniu czw., 9.03.2017 o 12:16 Mikolaj Magnuski <notifications@github.com>
napisał(a):

**Comment by mmagnuski** [comment]
To w takim razie nie tylko w złe miejsce ale i złą pracę. :) Dostała Pani maila z informacjami o pracy domowej?
* [tutaj wrzucamy pracę domową](https://github.com/mmagnuski/EEG01/issues/1)
* [a tutaj szukamy pomocy gdy nam się nie udaje pracy domowej zrealizować](https://github.com/mmagnuski/EEG01/issues/2)

**Comment by mazaw** [comment]
Rzeczywiście jest, dziękuję!

W dniu czw., 9.03.2017 o 12:30 Mikolaj Magnuski <notifications@github.com>
napisał(a):
